version: '3'

services:
  nginx:
    container_name: nginx  
    build:
      context: ./nginx
    restart: unless-stopped
    ports:
      - "443:443"
    networks:
      - inception_net
    volumes:
      - wordpress:/var/www/html

  wordpress:
    container_name: wordpress  
    build:
      context: ./wordpress  
    restart: unless-stopped
    env_file: .env
    networks:
      - inception_net
    volumes:
      - wordpress:/var/www/html

  mariadb:
    container_name: mariadb  
    build:
      context: ./mariadb  
    restart: unless-stopped
    env_file: .env
    networks:
      - inception_net
    volumes:
      - mariadb:/var/lib/mysql
  adminer:
    container_name: adminer  
    build:
      context: ./adminer  
    restart: unless-stopped
    networks:
      - inception_net
  static_site:
    container_name: static_site  
    build:
      context: ./static_site  
    restart: unless-stopped
    networks:
      - inception_net
networks:
  inception_net:
    driver: bridge

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sjouan/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/sjouan/data/mariadb